// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-4kBeuGTUGA-cCA-WYJ6UX3NE3Wki87k',
    appId: '1:847140726076:web:52824fa992d3bde895ea39',
    messagingSenderId: '847140726076',
    projectId: 'canisacademiabd',
    authDomain: 'canisacademiabd.firebaseapp.com',
    storageBucket: 'canisacademiabd.firebasestorage.app',
    measurementId: 'G-L5P4N3QW3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjMrNTwmhbTkhDlo3ul9juh5qzXmroUg0',
    appId: '1:847140726076:android:062f79ffecc8caa895ea39',
    messagingSenderId: '847140726076',
    projectId: 'canisacademiabd',
    storageBucket: 'canisacademiabd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP3icwequJWOVGscGUsSLb6YbaIYHEpaw',
    appId: '1:847140726076:ios:953b8eb947a5298895ea39',
    messagingSenderId: '847140726076',
    projectId: 'canisacademiabd',
    storageBucket: 'canisacademiabd.firebasestorage.app',
    iosBundleId: 'com.example.canisacademia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP3icwequJWOVGscGUsSLb6YbaIYHEpaw',
    appId: '1:847140726076:ios:953b8eb947a5298895ea39',
    messagingSenderId: '847140726076',
    projectId: 'canisacademiabd',
    storageBucket: 'canisacademiabd.firebasestorage.app',
    iosBundleId: 'com.example.canisacademia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-4kBeuGTUGA-cCA-WYJ6UX3NE3Wki87k',
    appId: '1:847140726076:web:62c556976cd881ae95ea39',
    messagingSenderId: '847140726076',
    projectId: 'canisacademiabd',
    authDomain: 'canisacademiabd.firebaseapp.com',
    storageBucket: 'canisacademiabd.firebasestorage.app',
    measurementId: 'G-MBDSCTNK6M',
  );
}
